{
 "title": "Citizerve",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Citizen API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage (Citizen API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"citizenapi\"}[5m])"
    }
   ]
  },
  {
   "title": "Container Memory Usage (Citizen API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"citizenapi\"}[5m])"
    }
   ]
  },
  {
   "title": "Avg. Response Time (last 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_response_latency_milliseconds_sum{}[5m])) / sum(rate(api_response_latency_milliseconds_count{}[5m]))"
    }
   ]
  },
  {
   "title": "API call rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_request_count_total{}[5m]))"
    }
   ]
  },
  {
   "title": "Avg. GC Duration (Citizen API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{exported_app=\"citizerve-citizenapi\"}[5m])) /  sum(rate(nodejs_gc_duration_seconds_count{exported_app=\"citizerve-citizenapi\"}[5m]))"
    }
   ]
  },
  {
   "title": "Citizen API Heap Size Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{exported_app=\"citizerve-citizenapi\"}"
    }
   ]
  },
  {
   "title": "Resource API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage (Resource API)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container=\"resourceapi\"}[5m])"
      }
     ]
    },
    {
     "title": "Container Memory Usage (Resource API)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(container_memory_usage_bytes{container=\"resourceapi\"}[5m])"
      }
     ]
    },
    {
     "title": "Avg. Response Time (last 5 mins)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(api_response_time_duration_milliseconds_sum{}[5m])) / sum(rate(api_response_time_duration_milliseconds_count{}[5m]))"
      }
     ]
    },
    {
     "title": "Resource API Heap Size Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{exported_app=\"citizerve-resourceapi\"}"
      }
     ]
    },
    {
     "title": "Avg. GC Duration (ResourceAPI)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(nodejs_gc_duration_seconds_sum{exported_app=\"citizerve-resourceapi\"}[5m])) /  sum(rate(nodejs_gc_duration_seconds_count{exported_app=\"citizerve-resourceapi\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs and Traces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Citizen API Last 20 Log Entries",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expression": "fields @timestamp, @message\n| filter kubernetes.namespace_name like /citizerve/\n| filter kubernetes.container_name like /citizenapi/\n| sort @timestamp desc\n| limit 20",
       "logGroupNames": [
        "/aws/containerinsights/mcpeks2/application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "Resource API Last 20 Log Entries",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expression": "fields @timestamp, @message\n| filter kubernetes.namespace_name like /citizerve/\n| filter kubernetes.container_name like /resourceapi/\n| sort @timestamp desc\n| limit 20",
       "logGroupNames": [
        "/aws/containerinsights/mcpeks2/application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "Citizen API Last 20 Log Errors",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expression": "fields @timestamp, @message\n| filter kubernetes.namespace_name like /citizerve/\n| filter kubernetes.container_name like /citizenapi/\n| filter @message not like /stdout/\n| sort @timestamp desc\n| limit 20",
       "logGroupNames": [
        "/aws/containerinsights/mcpeks2/application"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "Citizen API Traces",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "group": {
        "GroupARN": "arn:aws:xray:us-east-2:886674496073:group/Default",
        "GroupName": "Default",
        "InsightsConfiguration": {
         "InsightsEnabled": false,
         "NotificationsEnabled": false
        }
       },
       "query": "service(\"CitizenAPI\")",
       "region": "default"
      }
     ]
    }
   ]
  }
 ]
}