apiVersion: v1
kind: ConfigMap
metadata:
  name: citizerve-configmap
  namespace: citizerve
data:
  NODE_ENV: eks
  OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://zipkin-service:9411/api/v2/spans
  USE_ZIPKIN: 'false'
  COLLECTOR_ZIPKIN_HOST_PORT: ':9411'
  COLLECTOR_OTLP_ENABLED: 'true'
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://my-collector-xray-collector.prometheus.svc.cluster.local:4317'
