{
 "title": "Citizerve",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Citizen API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API call rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(api_request_count_total{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Response Latency - Citizen API (last 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_response_latency_milliseconds_sum{}[5m])) / sum(rate(api_response_latency_milliseconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Citizen API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"citizenapi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Citizen API Heap Size Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{exported_app=\"citizerve-citizenapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. GC Duration (Citizen API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{exported_app=\"citizerve-citizenapi\"}[5m])) /  sum(rate(nodejs_gc_duration_seconds_count{exported_app=\"citizerve-citizenapi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Container CPU Usage (Resource API)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"resourceapi\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Response Time - Resource API (last 5 mins)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_response_time_duration_milliseconds_sum{}[5m])) / sum(rate(api_response_time_duration_milliseconds_count{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource API Heap Size Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{exported_app=\"citizerve-resourceapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. GC Duration (ResourceAPI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(nodejs_gc_duration_seconds_sum{exported_app=\"citizerve-resourceapi\"}[5m])) /  sum(rate(nodejs_gc_duration_seconds_count{exported_app=\"citizerve-resourceapi\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}